name: Publish
on:
  workflow_dispatch:
  release:
    types: [ prereleased, released ]

jobs:
  release:
    name: Publish library
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Deploy to Sonatype
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          export ORG_GRADLE_PROJECT_VERSION_NAME=${NEW_VERSION}
          echo "DSC_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
          ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Update README
        run: ./.github/version.sh "${{ env.DSC_VERSION }}"

      - name: Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "./README.md"
          author_name: Jordon de Hoog
          author_email: jordon.dehoog@gmail.com
          message: "Update README for release ${{ env.DSC_VERSION }}"
          push: true